package EchoApp;


/**
* EchoApp/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* Wednesday, 6 June 2018 15:39:34 o'clock EAT
*/

public interface EchoOperations 
{
  String echoString ();
} // interface EchoOperations
